solarized:
  theme:     dark
title: Tyrone's art store
author: tyrone
email: tyrinfern@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Art store that makes a wallpaper consisting of 2 of my paintings for $2.
  
  
 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
